use_lmdb: False

DATA:
  MAX_SAMPLE_INTERVAL: 120
  SEARCH:
    NUMBER: 1
    # CENTER_JITTER: 4.5
    # FACTOR: 5.0
    # SCALE_JITTER: 0.5
    # SIZE: 384
  # STD:
  # - 0.229
  # - 0.224
  # - 0.225
  TEMPLATE:
    NUMBER: 2
    CENTER_JITTER: 0
    FACTOR: 2.0
    SCALE_JITTER: 0
    SIZE: 192
  # PREV_TEMPLATE:
    # NUMBER: 3
  TRAIN:
    DATASETS_NAME:
      - TNL2K_Lang
      - LASOT_Lang
      # - RefCOCO14
      - OTB_Lang
      # - TRACKINGNET
    DATASETS_RATIO:
      - 6
      - 6
      # - 6
      - 1
    SAMPLE_PER_EPOCH: 50000
  VAL:
    DATASETS_NAME:
      # - TNL2K_Lang
      # - LASOT_Lang
      - OTB_Lang
      # - TRACKINGNET
    DATASETS_RATIO:
    - 1
    SAMPLE_PER_EPOCH: 10000




env:
  workspace_dir: '/data1/lihaobo/tracking/'
  lasot_dir: '/data1/lihaobo/tracking/data/lasot'
  tnl2k_dir: '/data1/lihaobo/tracking/data/TNL2K_CVPR2021'
  otb_lang_dir: '/data1/lihaobo/tracking/data/OTB_lang'

  # tensorboard_dir: '/home/yz/tcsvt/MMTrack/tensorboard'
  # trackingnet_dir: '/data1/lihaobo/tracking/data/trackingnet'
  # got10k_dir: '/home/yz/tcsvt/MMTrack/data/got10k/train'
  # got10k_val_dir: '/home/yz/tcsvt/MMTrack/data/got10k/val'
  # lasot_lmdb_dir: '/home/yz/tcsvt/MMTrack/data/lasot_lmdb'
  # got10k_lmdb_dir: '/home/yz/tcsvt/MMTrack/data/got10k_lmdb'
  # trackingnet_lmdb_dir: '/home/yz/tcsvt/MMTrack/data/trackingnet_lmdb'
  # coco_dir: '/home/yz/tcsvt/MMTrack/data/coco'
  # coco_lmdb_dir: '/home/yz/tcsvt/MMTrack/data/coco_lmdb'
  # lvis_dir: ''
  # sbd_dir: ''
  # imagenet_dir: '/home/yz/tcsvt/MMTrack/data/vid'
  # imagenet_lmdb_dir: '/home/yz/tcsvt/MMTrack/data/vid_lmdb'
  # imagenetdet_dir: ''
  # ecssd_dir: ''
  # hkuis_dir: ''
  # msra10k_dir: ''
  # davis_dir: '/home/yz/tcsvt/MMTrack/data/davis'
  # youtubevos_dir: '/home/yz/tcsvt/MMTrack/data/youtubevos'
  # tracking_masks_dir: '/home/yz/tcsvt/MMTrack/data/tracking_masks'
  
  # refer_youtubevos_dir: '/home/yz/tcsvt/MMTrack/data/refer_youtubevos'
  # ref_coco_dir: '/home/yz/tcsvt/MMTrack/data/ref_coco'